---

  language: python
  python:
    - "3.8"

  sudo: required

  services:
    - docker

  addons:
    apt:
      packages:
      - python-pip

  jobs:
    include:
      - stage: "test"
        name: "Test"
        script:
          - pip install poetry tox
          - tox

      - stage: "build"
        name: "Build and publish"
        if: tag IS present
        script:
          - make build VERSION=$TRAVIS_TAG
          - make publish VERSION=$TRAVIS_TAG
