---

- name: Pull image
  docker_image:
    name: "{{ shortner_image }}:{{ shortner_version }}"
    source: pull

- name: Update service
  docker_swarm_service:
    name: "{{ shortner_stack }}_server"
    image: "{{ shortner_image }}:{{ shortner_version }}"
    replicas: "{{ shortner_replicas|default(1) }}"
