---

- name: Prepare folders
  file: path={{ item }} state=directory
  with_items:
    - "{{ shortner_service_dir }}"

- name: Assemble config files
  template: src={{ item.src }}.j2 dest={{ item.dest }}
  with_items:
    - src: docker-compose.yml
      dest: "{{ shortner_service_dir }}/docker-compose.yml"
    - src: .env
      dest: "{{ shortner_service_dir }}/.env"

- name: Pull image
  docker_image:
    name: "{{ shortner_image }}:{{ shortner_version }}"
    source: pull

- name: Deploy stack
  docker_stack:
    state: present
    name: "{{ shortner_stack }}"
    compose:
      - "{{ shortner_service_dir }}/docker-compose.yml"
