---

- hosts: servers
  become: true

  vars:
    domain: clayman.pro

    consul_host: "consul.service.consul"
    consul_port: "8500"

    private_network: "{{ ansible_eth1['ipv4'] }}"

    shortner_domain: "short.{{ domain }}"
    shortner_sentry_dsn: ""

    shortner_image: clayman083/shortner
    shortner_version: "{{ lookup('env','SHORTNER_VERSION')|default('latest') }}"

    shortner_replicas: 1

  tasks:
    - name: Pull image
      docker_image:
        name: "{{ shortner_image }}:{{ shortner_version }}"
        source: pull

    - name: Update service
      docker_swarm_service:
        name: shortner
        image: "{{ shortner_image }}:{{ shortner_version }}"
        command: python3 -m shortner server run
        args:
          - "--tags={{ env }}"
          - "--tags=traefik.enable=true"
          - "--tags=traefik.http.routers.shortner.rule=Host(`{{ shortner_domain }}`)"
          - "--tags=traefik.http.routers.shortner.entrypoints=web"
          - "--tags=traefik.http.routers.shortner.service=shortner"
          - "--tags=traefik.http.routers.shortner.middlewares=shortner-redirect@consulcatalog"
          - "--tags=traefik.http.middlewares.shortner-redirect.redirectscheme.scheme=https"
          - "--tags=traefik.http.middlewares.shortner-redirect.redirectscheme.permanent=true"
          - "--tags=traefik.http.routers.shortner-secure.rule=Host(`{{ shortner_domain }}`)"
          - "--tags=traefik.http.routers.shortner-secure.entrypoints=websecure"
          - "--tags=traefik.http.routers.shortner-secure.service=shortner"
          - "--tags=traefik.http.routers.shortner-secure.tls=true"
          - "--tags=traefik.http.routers.shortner-secure.tls.certresolver=acmeresolver"
        dns:
          - "{{ private_network.address }}"
        env:
          CONSUL_HOST: "{{ consul_host }}"
          CONSUL_PORT: "{{ consul_port }}"
        logging:
          driver: syslog
          options:
            syslog-address: unixgram:///dev/log
            tag: shortner
        networks:
          - backend
        replicas: "{{ shortner_replicas|default(1) }}"
        limits:
          cpus: '0.50'
          memory: 64M
        reservations:
          cpus: '0.25'
          memory: 32M

