name: Release and deploy

on:
  create:
    tags:
      - v*

jobs:
  run_tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-python@v1
        with:
          python-version: '3.8'
          architecture: 'x64'

      - name: Install requirements
        # Устанавливаем зависимости
        run: pip install poetry tox

      - name: Run tests
        run: tox

  publish_image:
    needs: [run_tests]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Publish to Docker Repository
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: clayman083/shortner
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tag_names: true

      - name: Send notification to Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.repository }} event ${{ github.event_name }} status - ${{ job.status }}.

  deploy:
    needs: [publish_image]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: set ansible config secrets
        env:
          SSH_KEY: ${{ secrets.SSH_KEY }}
        run: |
          mkdir .ssh
          echo "$SSH_KEY" > .ssh/id_rsa
          chmod 600 .ssh/id_rsa

      - name: run deploy playbook
        run: |
          ansible-playbook -i ansible/inventory ansible/deploy.yml

      - name: Send notification to Telegram
        if: always()
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT }}
          token: ${{ secrets.TELEGRAM_TOKEN }}
          args: ${{ github.repository }} deploy - ${{ job.status }}.
